import type { PopupBounds } from './popup.interface'

const bounds: PopupBounds[] = [
  {
    bottom: 'none',
    inset: 'none',
    left: 'center',
    name: 'bottom',
    right: 'none',
    top: 'bottom',
  },
  {
    bottom: 'none',
    inset: 'left',
    left: 'none',
    name: 'bottom-left',
    right: 'left',
    top: 'bottom',
  },
  {
    bottom: 'none',
    inset: 'right',
    left: 'right',
    name: 'bottom-right',
    right: 'none',
    top: 'bottom',
  },
  {
    bottom: 'none',
    inset: 'none',
    left: 'center',
    name: 'center',
    right: 'none',
    top: 'middle',
  },
  {
    bottom: 'none',
    inset: 'none',
    left: 'none',
    name: 'left',
    right: 'left',
    top: 'middle',
  },
  {
    bottom: 'none',
    inset: 'bottom',
    left: 'none',
    name: 'left-bottom',
    right: 'left',
    top: 'bottom',
  },
  {
    bottom: 'top',
    inset: 'top',
    left: 'none',
    name: 'left-top',
    right: 'left',
    top: 'none',
  },
  {
    bottom: 'none',
    inset: 'none',
    left: 'center',
    name: 'middle',
    right: 'none',
    top: 'middle',
  },
  {
    bottom: 'none',
    inset: 'none',
    left: 'right',
    name: 'right',
    right: 'none',
    top: 'middle',
  },
  {
    bottom: 'none',
    inset: 'bottom',
    left: 'right',
    name: 'right-bottom',
    right: 'none',
    top: 'bottom',
  },
  {
    bottom: 'top',
    inset: 'top',
    left: 'right',
    name: 'right-top',
    right: 'none',
    top: 'none',
  },
  {
    bottom: 'top',
    inset: 'none',
    left: 'center',
    name: 'top',
    right: 'none',
    top: 'none',
  },
  {
    bottom: 'top',
    inset: 'left',
    left: 'none',
    name: 'top-left',
    right: 'left',
    top: 'none',
  },
  {
    bottom: 'top',
    inset: 'right',
    left: 'right',
    name: 'top-right',
    right: 'none',
    top: 'none',
  },
]

export default bounds
